LanchesMac/Models/Pedido.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KiDeliciasLanches.Models
{
    public class Pedido
    {
        public int PedidoId { get; set; }

        [Required(ErrorMessage = "Informe o nome")]
        [StringLength(50)]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Informe o sobrenome")]
        [StringLength(50)]
        public string SobreNome { get; set; }

        [Required(ErrorMessage ="Informe o endereço")]
        [StringLength(100)]
        [Display(Name = "Endereço")]
        public string Endereco1 { get; set; }

        [StringLength(100)]
        [Display(Name ="Complemento")]
        public string Endereco2 { get; set; }

        [Required(ErrorMessage ="Informe o seu CEP")]
        [Display(Name ="CEP")]
        [StringLength(10, MinimumLength = 8)]
        public string Cep { get; set; }

        [StringLength(20)]
        [Required(ErrorMessage = "Informe a Unidade Federativa do Estado")]
        [Display(Name ="UF")]
        public string Estado { get; set; }

        [StringLength(50)]
        public string Cidade { get; set; }

        [Required(ErrorMessage ="Informe o seu telefone")]
        [StringLength(25, MinimumLength = 10)]
        [DataType(DataType.PhoneNumber)]
        public string Telefone { get; set; }

        [Required(ErrorMessage="Informe o email")]
        [StringLength(50)]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|""(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*"")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])",
            ErrorMessage = "O email não possui um formato válido")]
        [Display(Name ="E-Mail")]
        public string Email { get; set; }

        [ScaffoldColumn(false)]
        [Column(TypeName="decimal(18,2)")]
        [Display(Name ="Total do Pedido")]
        public decimal PedidoTotal { get; set; }

        [ScaffoldColumn(false)]
        [Display(Name ="Itens no Pedido")]
        public int TotalItensPedidos { get; set; }

        [Required(ErrorMessage = "Data Inválida")]
        [Display(Name ="Data do Pedido")]
        [DataType(DataType.Text)]
        [DisplayFormat(DataFormatString ="{0: dd/MM/yyyy hh:mm}", ApplyFormatInEditMode = true)]
        public DateTime PedidoEnviado { get; set; }
       
        [Display(Name ="Data do Envio")]
        [DataType(DataType.Text)]
        [DisplayFormat(DataFormatString ="{0: dd/MM/yyyy hh:mm}", ApplyFormatInEditMode = true)]
        public DateTime? PedidoEntregueEm { get; set; }

        public List<PedidoDetalhe> PedidoItens { get; set; }
    }
}

LanchesMac/Controllers/CarrinhoCompraController.cs
using KiDeliciasLanches.Models;
using KiDeliciasLanches.Repositories.Interfaces;
using KiDeliciasLanches.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Drawing.Text;

namespace KiDeliciasLanches.Controllers
{
    [Authorize]
    public class CarrinhoCompraController : Controller
    {
        private readonly ILancheRepository _lancheRepository;

        private readonly ICarrinhoCompraRepository _carrinhoCompraRepository;

        public CarrinhoCompraController(ILancheRepository lancheRepository,
            ICarrinhoCompraRepository carrinhoCompraRepository)
        {
            _lancheRepository = lancheRepository;
            _carrinhoCompraRepository = carrinhoCompraRepository;
        }

        public IActionResult Index()
        {
            var itens = _carrinhoCompraRepository.GetCarrinhoCompraItens();
            _carrinhoCompraRepository.CarrinhoCompraItems = itens;

            var carrinhoCompraVM = new CarrinhoCompraViewModel
            {
                CarrinhoCompra = (CarrinhoCompra)_carrinhoCompraRepository,
                CarrinhoCompraTotal = _carrinhoCompraRepository.GetCarrinhoCompraTotal()
            };

            return View(carrinhoCompraVM);
        }

        public IActionResult AdicionarNoCarrinhoCompra(int lancheId)
        {
            var lancheSelecionado =
                _lancheRepository.Lanches.SingleOrDefault(x => x.LancheId == lancheId);

            if (lancheSelecionado != null)
            {
                _carrinhoCompraRepository.AdicionarAoCarrinho(lancheSelecionado);
            }

            return RedirectToAction("Index");
        }

        public IActionResult RemoverItemDoCarrinhoCompra(int lancheId)
        {
            var lancheSelecionado =
                _lancheRepository.Lanches.FirstOrDefault(x => x.LancheId == lancheId);

            if (lancheSelecionado != null)
            {
                _carrinhoCompraRepository.RemoverDoCarrinho(lancheSelecionado);
            }

            return RedirectToAction("Index");
        }

        public IActionResult LimparCarrinhoCompra()
        {
            _carrinhoCompraRepository.LimparCarrinho();
            return RedirectToAction("Index");
        }
    }
}

LanchesMac/Controllers/PedidoController.cs
using KiDeliciasLanches.Models;
using KiDeliciasLanches.Repositories.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace KiDeliciasLanches.Controllers
{
    public class PedidoController : Controller
    {
        private readonly IPedidoRepository _pedidoRepository;
        private readonly ICarrinhoCompraRepository _carrinhoCompraRepository;

        public PedidoController(IPedidoRepository pedidoRepository, ICarrinhoCompraRepository carrinhoCompraRepository)
        {
            _pedidoRepository = pedidoRepository;
            _carrinhoCompraRepository = carrinhoCompraRepository;
        }

        [HttpGet]
        [Authorize]
        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Checkout(Pedido pedido)
        {
            int totalItensPedido = 0;
            decimal precoTotalPedido = 0.0m;

            List<CarrinhoCompraItem> items = _carrinhoCompraRepository.GetCarrinhoCompraItens();
            _carrinhoCompraRepository.CarrinhoCompraItems = items;

            if(_carrinhoCompraRepository.CarrinhoCompraItems.Count == 0)
            {
                ModelState.AddModelError("","Seu carrinho está vazio, que tal adicionar um lanche...");
                return View(pedido);
            }

            foreach(var item in items)
            {
                totalItensPedido += item.Quantidade;
                precoTotalPedido += (item.Lanche.Preco * item.Quantidade);
            }

            pedido.TotalItensPedidos = totalItensPedido;
            pedido.PedidoTotal = precoTotalPedido;

            if(ModelState.IsValid)
            {
                _pedidoRepository.CriarPedido(pedido);
                ViewBag.CheckoutCompletoMensagem = "Obrigado pelo seu pedido :)";
                ViewBag.TotalPedido = _carrinhoCompraRepository.GetCarrinhoCompraTotal();

                _carrinhoCompraRepository.LimparCarrinho();

                return View("~/Views/Pedido/CheckoutCompleto.cshtml", pedido);
            }

            return View(pedido);
        }
    }
}

LanchesMac/Views/Pedido/Checkout.cshtml
@model Pedido

<div class="card text-white" style="padding:10px; background-color: #192023">
    <h3>Você está a um passo de concluir seu pedido!</h3>
    <div class="card" style="padding:10px; border-color:white; background-color: #192023">
        <form asp-action="Checkout" method="post" class="form-horizontal" role="form">
            <partial name="_FormularioPedido"/>
            <br />
            <div class="row">
                <div class="form-group col-md-6">
                    <input class="btn btn-outline-success" type="submit" value="Incluir pedido" />
                </div>
                <div class="text-end form-group col-md-6">
                    <a class="btn btn-outline-info" asp-controller="CarrinhoCompra" asp-action="Index">Retornar ao carrinho</a>
                </div>
            </div>
        </form>
    </div>
</div>

LanchesMac/Views/Pedido/CheckoutCompleto.cshtml
@model Pedido

<div class="container-fluid">
    <div class="row">
        <div class="card text-white" style="padding-bottom:10px; padding-top:10px; background-color:#192023">            
            <div class="col-5">
                <div class="row">
                    <div class="col-1">
                        <img src="~/imagens/visto.png" class="img-fluid" style="padding-bottom:8px; max-width:50px; max-height:50px" />
                    </div>
                    <div class="col-10" style="margin-left:10px">
                        <h3>@ViewBag.CheckoutCompletoMensagem</h3>
                    </div>
                </div>
            </div>
            <div class="card" style="background-color:#192023">
                <div class="card-body border" style="color:white">
                    <p>Cliente: <strong>@Model.Nome @Model.SobreNome</strong></p>
                    <p>Data do pedido: <strong>@Model.PedidoEnviado</strong></p>
                    <p class="border-bottom" style="color:white">
                        Número do Pedido: <strong>@Model.PedidoId</strong>
                    </p>
                    <br />
                    <div style="overflow-x: auto;">
                        <table class="table table-striped table-hover table-dark">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>Quantidade</th>
                                    <th>Lanche</th>
                                    <th class="text-end">Preço</th>
                                    <th class="text-end" style="padding-right:10px">SubTotal</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.PedidoItens)
                                {
                                    <tr>
                                        <td><img src="@item.Lanche.ImagemUrl" class="img-fluid" style="max-width:40px; max-height:40px" /></td>
                                        <td>@item.Quantidade</td>
                                        <td>@item.Lanche.Nome</td>
                                        <td class="text-end">@item.Lanche.Preco</td>
                                        <td class="text-end" style="padding-right:10px">@((item.Quantidade * item.Lanche.Preco).ToString("c"))</td>
                                    </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr class="text-start">
                                    <td class="text-end" colspan="4">
                                        <b>Valor Total: </b>
                                    </td>
                                    <td class="text-end" style="padding-right:10px">
                                        <b>@(((decimal)ViewBag.TotalPedido).ToString("C2"))</b>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
            <br />
            <div class="card-footer border" style="background-color:#192023; color:white">
                <div class="form-group" style="text-align: center">
                    <h3>
                        <a class="nav-link text-info" asp-controller="Home" asp-action="Index">Retornar</a>
                    </h3>
                </div>
            </div>
        </div>
    </div>
</div>