LanchesMac/Areas/Admin/Controllers/AdminPedidosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KiDeliciasLanches.Context;
using KiDeliciasLanches.Models;
using Microsoft.AspNetCore.Authorization;
using ReflectionIT.Mvc.Paging;
using KiDeliciasLanches.ViewModels;
using KiDeliciasLanches.Repositories.Interfaces;
using KiDeliciasLanches.Repositories;

namespace KiDeliciasLanches.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class AdminPedidosController : Controller
    {
        private readonly AppDbContext _context;
        private readonly ICarrinhoCompraRepository _carrinhoCompraRepository;
        private readonly IPedidoRepository _pedidoRepository;

        public AdminPedidosController(AppDbContext context, ICarrinhoCompraRepository carrinhoCompraRepository, IPedidoRepository pedidoRepository)
        {
            _context = context;
            _carrinhoCompraRepository = carrinhoCompraRepository;
            _pedidoRepository = pedidoRepository;
        }

        public IActionResult ItensPedido(int? id)
        {
            var pedido = _context.Pedidos.Include(pd => pd.PedidoItens)
                .ThenInclude(l => l.Lanche).FirstOrDefault(p => p.PedidoId == id);

            if (pedido == null)
            {
                Response.StatusCode = 404;
                return View("PedidoNotFound", id.Value);
            }

            PedidoLancheViewModel pedidoLanches = new PedidoLancheViewModel()
            {
                Pedido = pedido,
                PedidoDetalhes = pedido.PedidoItens
            };

            return View(pedidoLanches);
        }

        public async Task<IActionResult> Index(string filter, int pageindex = 1, string sort = "Nome")
        {
            var resultado = _context.Pedidos.AsNoTracking().AsQueryable();

            if (!string.IsNullOrWhiteSpace(filter))
            {
                resultado = resultado.Where(p => p.Nome.Contains(filter));
            }

            var model = await PagingList.CreateAsync(resultado, 5, pageindex, sort, "Nome");
            model.RouteValue = new RouteValueDictionary { { "filter", filter } };

            return View(model);
        }

        // GET: Admin/AdminPedidos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pedidos == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos
                .FirstOrDefaultAsync(m => m.PedidoId == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // GET: Admin/AdminPedidos/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PedidoId,Nome,SobreNome,Endereco1,Endereco2,Cep,Estado,Cidade,Telefone,Email,PedidoEnviado,PedidoEntregueEm")] Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pedido);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pedido);
        }

        // GET: Admin/AdminPedidos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pedidos == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos.FindAsync(id);
            if (pedido == null)
            {
                return NotFound();
            }
            return View(pedido);
        }

        // POST: Admin/AdminPedidos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PedidoId,Nome,SobreNome,Endereco1,Endereco2,Cep,Estado,Cidade,Telefone,Email,PedidoEnviado,PedidoEntregueEm")] Pedido pedido)
        {
            var pedidoItens = pedido.TotalItensPedidos;

            if (id != pedido.PedidoId)
            {
                return NotFound();
            }                      

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pedido);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PedidoExists(pedido.PedidoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }            

            return View(pedido);
        }

        // GET: Admin/AdminPedidos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Pedidos == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos
                .FirstOrDefaultAsync(m => m.PedidoId == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // POST: Admin/AdminPedidos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Pedidos == null)
            {
                return Problem("Entity set 'AppDbContext.Pedidos'  is null.");
            }
            var pedido = await _context.Pedidos.FindAsync(id);
            if (pedido != null)
            {
                _context.Pedidos.Remove(pedido);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PedidoExists(int id)
        {
            return _context.Pedidos.Any(e => e.PedidoId == id);
        }
    }
}

LanchesMac/Areas/Admin/Views/AdminPedidos/Create.cshtml
@model Pedido

@{
    ViewData["Title"] = "Criar Pedido";
    @ViewBag.TotalItensPedidos
}

<div class="card text-white" style="padding:10px; background-color: #192023">
    <h3>Criar Pedido</h3>
    <div class="card" style="padding:10px; border-color:white; background-color: #192023">
        <form asp-action="Create" method="post" class="form-horizontal" role="form">
            <partial name="_FormularioPedido" />
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="PedidoEnviado" class="control-label"></label>
                    <input asp-for="PedidoEnviado" class="form-control" placeholder="DD/MM/AAAA 00:00" id="PedidoEnviado" />
                    <span asp-validation-for="PedidoEnviado" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="PedidoEntregueEm" class="control-label"></label>
                    <input asp-for="PedidoEntregueEm" class="form-control" placeholder="DD/MM/AAAA 00:00" id="PedidoEntregueEm" />
                    <span asp-validation-for="PedidoEntregueEm" class="text-danger"></span>
                </div>
            </div>
            <br />
            <p class="border-bottom" style="color:white"></p>
            <div class="row">
                <div class="form-group col-md-6">
                    <input class="btn btn-outline-success" type="submit" value="Criar Pedido" />
                </div>
                <div class="text-end form-group col-md-6">
                    <a class="btn btn-outline-info" asp-action="Index">Retornar</a>
                </div>
            </div>
        </form>
    </div>
</div>

LanchesMac/Areas/Admin/Views/AdminPedidos/Delete.cshtml
@model Pedido

@{
    ViewData["Title"] = "Delete";
}

<div class="container-fluid">
    <div class="row">
        <div class="card text-white" style="padding:10px; background-color:#192023">
            <div class="text-center">
                <h3>Tem certeza de que deseja excluir este Pedido?</h3>
            </div>
            <div class="card" style="padding:10px; border-color:white; background-color: #192023">
                <dl class="row" style="border-bottom-color:white">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Nome)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Nome)
                    </dd>

                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.SobreNome)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.SobreNome)
                    </dd>

                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Endereco1)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Endereco1)
                    </dd>

                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Endereco2)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Endereco2)
                    </dd>

                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Cep)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Cep)
                    </dd>

                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Estado)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Estado)
                    </dd>

                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Cidade)
                    </dt>

                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Cidade)
                    </dd>

                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Telefone)
                    </dt>

                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Telefone)
                    </dd>

                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Email)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Email)
                    </dd>

                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.PedidoEnviado)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.PedidoEnviado)
                    </dd>

                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.PedidoEntregueEm)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.PedidoEntregueEm)
                    </dd>
                </dl>
                <p class ="border-bottom" style="color:white"></p>
                <form asp-action="Delete">
                    <div class="row">
                        <div class="col-sm-6  text-start">
                            <input type="hidden" asp-for="PedidoId" />
                            <input type="submit" value="Delete" class="btn btn-outline-danger" />
                        </div>
                        <div class="col-sm-6  text-end">
                            <a asp-action="Index" class="btn btn-outline-info">Retornar</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

LanchesMac/Areas/Admin/Views/AdminPedidos/Details.cshtml
@model Pedido

@{
    ViewData["Title"] = "Detalhes";
}

<div class="container-fluid">
    <div class="row">
        <div class="card text-white" style="padding:10px; background-color:#192023">
            <div class="text-center">
                <h3>Detalhes do Pedido</h3>
            </div>
            <div class="card" style="padding:10px; border-color:white; background-color: #192023">
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Nome)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Nome)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.SobreNome)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.SobreNome)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Endereco1)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Endereco1)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Endereco2)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Endereco2)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Cep)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Cep)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Estado)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Estado)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Cidade)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Cidade)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Telefone)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Telefone)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Email)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Email)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.PedidoEnviado)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.PedidoEnviado)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.PedidoEntregueEm)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.PedidoEntregueEm)
                    </dd>
                </dl>
                <p class="border-bottom" style="color:white"></p>
                <div class="row">
                    <div class="col-6-sm col-md-6 col-lg-6 text-start">
                        <a asp-action="Edit" asp-route-id="@Model?.PedidoId" class="btn btn-outline-warning">Editar</a>
                    </div>
                    <div class="col-6-sm col-md-6 col-lg-6 text-end">
                        <a asp-action="Index" class="btn btn-outline-info">Retornar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

LanchesMac/Areas/Admin/Views/AdminPedidos/Edit.cshtml
@model Pedido

@{
    ViewData["Title"] = "Edit";
}

<div class="card text-white" style="padding:10px; background-color: #192023">
    <h3>Editar Pedido</h3>
    <div class="card" style="padding:10px; border-color:white; background-color: #192023">
        <form asp-action="Edit">
            <partial name="_FormularioPedido" />            
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="PedidoEnviado" class="control-label"></label>
                    <input asp-for="PedidoEnviado" class="form-control" placeholder="DD/MM/AAAA 00:00" id="PedidoEnviado" />
                    <span asp-validation-for="PedidoEnviado" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="PedidoEntregueEm" class="control-label"></label>
                    <input asp-for="PedidoEntregueEm" class="form-control" placeholder="DD/MM/AAAA 00:00" id="PedidoEntregueEm" />
                    <span asp-validation-for="PedidoEntregueEm" class="text-danger"></span>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="form-group col-md-6 text-start">
                    <input type="hidden" asp-for="PedidoId" />
                    <input type="submit" value="Salvar" class="btn btn-outline-primary" />
                </div>
                <div class="form-group col-md-6 text-end">
                    <a asp-action="Index" class="btn btn-outline-info">Retornar</a>
                </div>
            </div>
        </form>
    </div>
</div>

LanchesMac/Areas/Admin/Views/AdminPedidos/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<Pedido>

@{
    ViewData["Title"] = "Pedidos";
}

<div class="container-fluid">
    <div class="row">
        <div class="card text-white" style="background-color:#192023; padding:10px; width:100%">
            <h3>Pedidos</h3>
            <form method="get" class="form-inline">
                <div class="col-sm-4">
                    <input name="filter" class="form-control" placeholder="Buscar Pedido"
                           value="@Model.RouteValue["Filter"]" />
                </div>
                <div style="padding-top:10px">
                    <button type="submit" class="btn btn-outline-info">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>Buscar
                    </button>
                </div>
            </form>
            &nbsp;
            <div>
                Total de Pedidos : @Model.TotalRecordCount
                <vc:pager paging-list="@Model"></vc:pager>
            </div>
            <p>
                <a asp-action="Create" class="btn btn-outline-primary">Criar Pedido</a>
            </p>
            <br />
            <div style="overflow-x: auto;">
                <table class="table table-striped table-hover table-dark">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Nome)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.SobreNome)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Endereco1)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Endereco2)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Cep)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Estado)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Cidade)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Telefone)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Email)
                            </th>
                            <th class="text-truncate">
                                @Html.DisplayNameFor(model => model.PedidoEnviado)
                            </th>
                            <th class="text-truncate">
                                @Html.DisplayNameFor(model => model.PedidoEntregueEm)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr class="text-truncate">
                                <td>
                                    @Html.DisplayFor(modelItem => item.Nome)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SobreNome)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Endereco1)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Endereco2)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Cep)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Estado)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Cidade)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Telefone)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Email)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PedidoEnviado)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PedidoEntregueEm)
                                </td>
                                <td>
                                    <a asp-action="Edit" asp-route-id="@item.PedidoId" class="text-warning">Editar</a> |
                                    <a asp-action="Delete" asp-route-id="@item.PedidoId" class="text-danger">Deletar</a> |
                                    <a asp-action="Details" asp-route-id="@item.PedidoId" class="text-primary">Detalhes</a> |                                    
                                    <a asp-action="ItensPedido" asp-route-id="@item.PedidoId" class="text-success">Itens</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

LanchesMac/Areas/Admin/Views/AdminPedidos/ItensPedido.cshtml
@model PedidoLancheViewModel


@{
    ViewData["Title"] = "Itens do Pedido";
    decimal totalPedido = 0;
}

<div class="container-fluid">
    <div class="row">
        <div class="card text-white" style="padding-bottom:10px; padding-top:10px; background-color:#192023">
            <div class="text-center">
                <h3>Itens do Pedido</h3>
            </div>
            <div class="card" style="background-color:#192023">

                <div class="card-body border" style="color:white">
                    <h5>Cliente : @Html.DisplayFor(model => Model.Pedido.Nome)</h5>
                    <h5>Data : @Html.DisplayFor(model => Model.Pedido.PedidoEnviado)</h5>
                    <h5>Entrega : @Html.DisplayFor(model => Model.Pedido.PedidoEntregueEm)</h5>
                    <h5>Pedido : @Html.DisplayFor(model => Model.Pedido.PedidoId)</h5>
                    <p class="border-bottom" style="color:white"></p>

                    <div class="card" style="background-color:#192023">
                        <div class="card-body border" style="color:white">
                            <div style="overflow-x: auto;">
                                <table class="table table-striped table-hover table-dark">
                                    <thead>
                                        <tr>
                                            <th></th>
                                            <th>Quantidade</th>
                                            <th>Lanche</th>
                                            <th class="text-end">Preço</th>
                                            <th class="text-end" style="padding-right:10px">SubTotal</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.Pedido.PedidoItens)
                                        {
                                            totalPedido += (item.Lanche.Preco * item.Quantidade);
                                            <tr>
                                                <td>
                                                    <img src="@item.Lanche.ImagemUrl" class="img-fluid" style="max-width:40px; max-height:40px">
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Quantidade)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Lanche.Nome)
                                                </td>

                                                <td align="right">
                                                    @string.Format("{0:C}", item.Lanche.Preco)
                                                </td>

                                                <td class="text-end">
                                                    @((item.Quantidade * item.Lanche.Preco).ToString("c"))
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                    <tfoot>
                                        <tr class="text-start">
                                            <td class="text-end" colspan="4">
                                                <b>Valor Total: </b>
                                            </td>
                                            <td class="text-end" style="padding-right:10px">
                                                <hb>@string.Format("{0:C}", @totalPedido)</hb>
                                            </td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="card-footer border" style="background-color:#192023; color:white">
                        <div class="form-group" style="text-align: center">
                            <h3>
                                <a asp-action="Index" class="text-info">Retornar</a>
                            </h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

LanchesMac/Areas/Admin/Views/AdminPedidos/PedidoNotFound.cshtml
@model int

@{
    ViewData["Title"] = "404 Not Foun";
}

<div class="alert alert-danger mt-1 mb-1">
    <h1>Error 404 - Not Found </h1>
    <hr />
    <h2>Pedido com o id = @Model não encontrado</h2>
</div>

<a asp-action="Index" asp-controller="AdminPedidos" class="btn btn-outline-success">
    <h2>Retornar para a lista de Pedidos</h2>
</a>